### ISSUE TITLE
mock objects of data structure

### ISSUE THREAD

**Issue by micah-prime** [snowex-hackweek/space-station#10]
We need mock objects of the data structure to allow plotting and analysis work to happen in tandem

**Comment by micah-prime** [comment]
![E2AD7F4D-767B-4644-B6A1-8534A490852F_1_102_o](https://user-images.githubusercontent.com/32111103/178831234-bf3c2c45-07b7-4d28-bf42-0113ce92c70c.jpeg)
![96660148-A988-43BE-9C9B-8FD08BF0CB2B_1_102_o](https://user-images.githubusercontent.com/32111103/178831264-16cd7a2a-805d-434e-8781-cf4d65725252.jpeg)

**Comment by Ibrahim-Ola** [comment]
The mock data structure was passed to the next subgroup. Job well done! @beautah

**Comment by Ibrahim-Ola** [comment]
The mock data structure was passed to the next subgroup. Job well done! @beautah
