### ISSUE TITLE
Start exploring met station data

### ISSUE THREAD

**Issue by rpalomaki** [snowex-hackweek/space-station#6]
Windroses, etc. Check out metloom package

**Comment by rpalomaki** [comment]
https://github.com/ARM-DOE/ACT for windrose code
Also a possibility to use plotly express

https://github.com/M3Works/metloom to grab station data

**Comment by rpalomaki** [comment]
I got plotly up and running in my jupyterhub after some installing a couple extensions. Great suggestion @beautah, this is a really simple way to get nice looking wind roses. Looking forward to using with the metloom package for the actual station data.

**Comment by dlhogan97** [comment]
Got the metloom package installed and pulling, super simple with @micah-prime documentation!

**Comment by rpalomaki** [comment]
Metloom + ARM windrose code
